# Generated by Django 2.1.3 on 2018-11-25 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0004_remove_group_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('module_num', models.PositiveIntegerField(verbose_name='Nr modułu')),
                ('course_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.CourseType', verbose_name='Typ kursu')),
            ],
            options={
                'verbose_name': 'Egzamin',
                'verbose_name_plural': 'Egzaminy',
            },
        ),
    ]
