# Generated by Django 2.1.3 on 2018-11-25 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_remove_group_start_date'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField(verbose_name='Nr zadania')),
                ('points', models.PositiveIntegerField(verbose_name='Punkty')),
                ('description', models.TextField(verbose_name='Treść zadania')),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.Exam', verbose_name='Egzamin')),
            ],
            options={
                'verbose_name': 'Zadanie',
                'verbose_name_plural': 'Zadania',
            },
        ),
        migrations.CreateModel(
            name='ExerciseStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(verbose_name='Zdobyte punkty')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Exercise', verbose_name='Zadanie')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Zadanie zrobione przez studenta',
                'verbose_name_plural': 'Zadania zrobione przez',
            },
        ),
    ]
