# Generated by Django 2.1.3 on 2018-11-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nazwa')),
            ],
            options={
                'verbose_name': 'Typ kursu',
                'verbose_name_plural': 'Typy kursów',
            },
        ),
    ]
