# Generated by Django 2.1.3 on 2018-11-25 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='start_date',
        ),
    ]
