# Generated by Django 2.1.3 on 2018-11-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exercise_exercisestudent'),
        ('teams', '0004_remove_group_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='exercises',
            field=models.ManyToManyField(through='exams.ExerciseStudent', to='exams.Exercise', verbose_name='Zadania'),
        ),
    ]
